# -*- coding: utf-8 -*-
"""revise_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ae9DCZ2RsOoB_1CprrOuvj2uiUD_Y3Pu
"""
#pip install nltk

import pandas as pd

'''
Parameters
'''

input_file = 'dataset.txt'
output_file = 'dataset2.txt'

dict_file = 'wordlist.10000.txt'

dict = pd.read_csv(dict_file, header=None)
dict_list = dict.values

with open(input_file, 'r') as file:
    file_content = file.read()

finished_mark ='@FED1@'
def insert_finished_mark(string, index=1):
  return string[:index] + finished_mark + string[index:]

from nltk.tokenize import word_tokenize
import nltk
import string
from nltk.tokenize.treebank import TreebankWordDetokenizer
nltk.download('punkt_tab')

#Check 2 tokens
def integration_step1(tokens):
  new_tokens = []
  skip = False
  for index, token in enumerate(tokens):
    if skip:
      skip = False
      continue
    if token.lower() in dict_list or token in string.punctuation:
      #print("1 " +token)
      new_tokens.append(token)
    else:
      if index+1 == len(tokens):
        combined_token = tokens[index-1] + token
        if combined_token.lower() in dict_list:
          new_tokens.pop()
          new_tokens.append(combined_token)
          #print("3 " +combined_token)
        else:
          new_tokens.append(token)
        return new_tokens
      else:
        combined_token = token + tokens[index+1]
        if combined_token.lower() in dict_list:
          new_tokens.append(combined_token)
          skip = True
          #print("2 " +combined_token)
        elif index != 0:
          combined_token = tokens[index-1] + token
          if combined_token.lower() in dict_list:
            new_tokens.pop()
            new_tokens.append(combined_token)
            #print("3 " +combined_token)
          else:
            new_tokens.append(token)
            #print("4a " +token)
        else:
          new_tokens.append(token)
          #print("4b " +token)
  return new_tokens

#Check 3 tokens
def integration_step2(tokens):
  if len(tokens) <= 2:
    return tokens
  new_tokens = []
  while len(tokens) > 0:
    token = tokens.pop(0)
    if token.lower() in dict_list:
      new_tokens.append(token)
    elif len(tokens) >= 2:
      combined_token = token + tokens[0] + tokens[1]
      if combined_token.lower() in dict_list:
        new_tokens.append(combined_token)
        tokens.pop(0)
        tokens.pop(0)
      else:
        new_tokens.append(token)
    else:
      new_tokens.append(token)
  return new_tokens

#Check punctuation
def integration_step3(sentence):
  return sentence.replace(' .', '.')

def process_text(sentence):
  tokens = word_tokenize(sentence)
  result = integration_step1(tokens)
  result = integration_step2(result)

  result = TreebankWordDetokenizer().detokenize(result)
  output = integration_step3(result)
  return output

import re

#match = re.search('\"(.*?)\"', file_content)
#matches = re.findall('(?<=\").*?(?=\")', file_content)
matches = re.findall('(?<=\")[0-9a-zA-Z]+.*?(?=\")', file_content)

new_content = file_content

for match in matches:
  processed_match = process_text(match)
  marked_processed_match = insert_finished_mark(processed_match)
  new_content = new_content.replace('"'+match, '"'+marked_processed_match, 1)
  #print(marked_processed_match)

#print(new_content)
new_content = new_content.replace(finished_mark, '')
#print(new_content)

print(new_content)
with open(output_file, "w") as text_file:
    text_file.write(new_content)

